// constants.js

// Power generated by one panel in kilowatts (kW)
const PANEL_POWER_KW = 0.61;

// Efficiency of the system (adjusted for losses)
const SYSTEM_EFFICIENCY = 0.789;

// Area occupied by one panel in square meters
const PANEL_AREA_M2 = 2.7;

// CO₂ saved per kWh in kg (annual)
const CO2_SAVED_PER_KWH = 0.5;

// Trees offset per 10 kg of CO2 saved (adjusted with 0.8 factor)
const TREE_FACTOR = 0.8;

// IVA
const TAX_RATE = 0.12;

// Panel warranty
const SYSTEM_LIFETIME_YEARS = 25;

// Cost per kilowatt in quetzales
const COST_PER_KW = 7500;